### ISSUE TITLE
FreshBoy’s Headspace链接指向网址似乎已经失效

### ISSUE THREAD

**Issue by ZhengliangDuanfang** [IsshikiHugh/zju-cs-asio#13]
All-Sum-in-One部分中，FreshBoy’s Headspace链接指向的网址为https://freshboy-cyh.github.io/，访问该网址跳转到404页面（见下图），且无论是否使用代理皆是如此。在GitHub中搜索freshboy-cyh.github.io仓库也无对应结果。

<img width="1290" alt="屏幕截图 2024-02-21 203807" src="https://github.com/IsshikiHugh/zju-cs-asio/assets/126074867/76b53398-0c2f-4d0d-9ad6-22c848248687">

我对GitHub Pages不是很熟悉，如表述模糊或有误，还请不吝指正。

**Comment by IsshikiHugh** [comment]
该链接确实过期了，已经修复！感谢！
