### ISSUE TITLE
在GitHub Page页面中，开头三个链接未能正确渲染

### ISSUE THREAD

**Issue by ZhengliangDuanfang** [IsshikiHugh/zju-cs-asio#17]
在 https://isshikihugh.github.io/zju-cs-asio/ 中浏览时，开头Page、Repository与Quick Jump三个链接似乎未能正确渲染，仍保持MarkDown的原始文本状态，见下图（Chrome中打开）。在Chrome、FireFox与Edge中尝试打开该页面均呈相同结果，F5刷新无效。

![photo1](https://github.com/IsshikiHugh/zju-cs-asio/assets/126074867/aa5d46b6-443c-407f-8ed7-a35a01f61ce7)

如果我表述有误，请不吝指正。

**Comment by IsshikiHugh** [comment]
感谢指出，已经修复。
